# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/MyIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImgLabel1 = QtWidgets.QLabel(self.groupBox)
        self.ImgLabel1.setObjectName("ImgLabel1")
        self.verticalLayout.addWidget(self.ImgLabel1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_openImg = QtWidgets.QPushButton(self.frame)
        self.pushButton_openImg.setObjectName("pushButton_openImg")
        self.verticalLayout_3.addWidget(self.pushButton_openImg)
        self.pushButton_openVideo = QtWidgets.QPushButton(self.frame)
        self.pushButton_openVideo.setObjectName("pushButton_openVideo")
        self.verticalLayout_3.addWidget(self.pushButton_openVideo)
        self.pushButton_openCamera = QtWidgets.QPushButton(self.frame)
        self.pushButton_openCamera.setObjectName("pushButton_openCamera")
        self.verticalLayout_3.addWidget(self.pushButton_openCamera)
        self.pushButton_Start1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_Start1.setEnabled(False)
        self.pushButton_Start1.setObjectName("pushButton_Start1")
        self.verticalLayout_3.addWidget(self.pushButton_Start1)
        self.pushButton_Start2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_Start2.setEnabled(False)
        self.pushButton_Start2.setObjectName("pushButton_Start2")
        self.verticalLayout_3.addWidget(self.pushButton_Start2)
        self.pushButton_videoResult = QtWidgets.QPushButton(self.frame)
        self.pushButton_videoResult.setEnabled(False)
        self.pushButton_videoResult.setObjectName("pushButton_videoResult")
        self.verticalLayout_3.addWidget(self.pushButton_videoResult)
        self.pushButton_Start3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_Start3.setEnabled(False)
        self.pushButton_Start3.setObjectName("pushButton_Start3")
        self.verticalLayout_3.addWidget(self.pushButton_Start3)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit1.setEnabled(True)
        self.lineEdit1.setObjectName("lineEdit1")
        self.horizontalLayout_2.addWidget(self.lineEdit1)
        self.label_to = QtWidgets.QLabel(self.frame)
        self.label_to.setEnabled(True)
        self.label_to.setObjectName("label_to")
        self.horizontalLayout_2.addWidget(self.label_to)
        self.lineEdit2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit2.setEnabled(True)
        self.lineEdit2.setObjectName("lineEdit2")
        self.horizontalLayout_2.addWidget(self.lineEdit2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.MyprogressBar = QtWidgets.QProgressBar(self.frame)
        self.MyprogressBar.setProperty("value", 24)
        self.MyprogressBar.setObjectName("MyprogressBar")
        self.verticalLayout_3.addWidget(self.MyprogressBar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ImgLabel2 = QtWidgets.QLabel(self.groupBox_2)
        self.ImgLabel2.setObjectName("ImgLabel2")
        self.verticalLayout_2.addWidget(self.ImgLabel2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 30))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_6 = QtWidgets.QMenu(self.menu)
        self.menu_6.setObjectName("menu_6")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_System = QtWidgets.QMenu(self.menubar)
        self.menu_System.setObjectName("menu_System")
        self.menu_Language = QtWidgets.QMenu(self.menu_System)
        self.menu_Language.setObjectName("menu_Language")
        self.menu_Help = QtWidgets.QMenu(self.menu_System)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_3.sizePolicy().hasHeightForWidth())
        self.menu_3.setSizePolicy(sizePolicy)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionTensorboard = QtWidgets.QAction(MainWindow)
        self.actionTensorboard.setObjectName("actionTensorboard")
        self.actionBaiduImage = QtWidgets.QAction(MainWindow)
        self.actionBaiduImage.setObjectName("actionBaiduImage")
        self.actionOpenData = QtWidgets.QAction(MainWindow)
        self.actionOpenData.setObjectName("actionOpenData")
        self.actionTFRecord = QtWidgets.QAction(MainWindow)
        self.actionTFRecord.setObjectName("actionTFRecord")
        self.actionsaa = QtWidgets.QAction(MainWindow)
        self.actionsaa.setObjectName("actionsaa")
        self.actionas_2 = QtWidgets.QAction(MainWindow)
        self.actionas_2.setObjectName("actionas_2")
        self.actionImageEditor = QtWidgets.QAction(MainWindow)
        self.actionImageEditor.setObjectName("actionImageEditor")
        self.actionsda = QtWidgets.QAction(MainWindow)
        self.actionsda.setObjectName("actionsda")
        self.actions = QtWidgets.QAction(MainWindow)
        self.actions.setObjectName("actions")
        self.actiondsa = QtWidgets.QAction(MainWindow)
        self.actiondsa.setObjectName("actiondsa")
        self.actionasdas = QtWidgets.QAction(MainWindow)
        self.actionasdas.setObjectName("actionasdas")
        self.actiondas = QtWidgets.QAction(MainWindow)
        self.actiondas.setObjectName("actiondas")
        self.actionasd = QtWidgets.QAction(MainWindow)
        self.actionasd.setObjectName("actionasd")
        self.actionads = QtWidgets.QAction(MainWindow)
        self.actionads.setObjectName("actionads")
        self.actionjupyter_Notebook = QtWidgets.QAction(MainWindow)
        self.actionjupyter_Notebook.setObjectName("actionjupyter_Notebook")
        self.actionDocument = QtWidgets.QAction(MainWindow)
        self.actionDocument.setObjectName("actionDocument")
        self.actionview1 = QtWidgets.QAction(MainWindow)
        self.actionview1.setObjectName("actionview1")
        self.actionview2 = QtWidgets.QAction(MainWindow)
        self.actionview2.setObjectName("actionview2")
        self.actionview3 = QtWidgets.QAction(MainWindow)
        self.actionview3.setObjectName("actionview3")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action2_2 = QtWidgets.QAction(MainWindow)
        self.action2_2.setObjectName("action2_2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.actionAskd = QtWidgets.QAction(MainWindow)
        self.actionAskd.setObjectName("actionAskd")
        self.actionEn = QtWidgets.QAction(MainWindow)
        self.actionEn.setObjectName("actionEn")
        self.actionCh = QtWidgets.QAction(MainWindow)
        self.actionCh.setObjectName("actionCh")
        self.actionJa = QtWidgets.QAction(MainWindow)
        self.actionJa.setObjectName("actionJa")
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.actionDoc = QtWidgets.QAction(MainWindow)
        self.actionDoc.setObjectName("actionDoc")
        self.actionBanben = QtWidgets.QAction(MainWindow)
        self.actionBanben.setObjectName("actionBanben")
        self.actionOpenImg = QtWidgets.QAction(MainWindow)
        self.actionOpenImg.setObjectName("actionOpenImg")
        self.actionOpenTarget = QtWidgets.QAction(MainWindow)
        self.actionOpenTarget.setObjectName("actionOpenTarget")
        self.actionOpenDataImgs = QtWidgets.QAction(MainWindow)
        self.actionOpenDataImgs.setObjectName("actionOpenDataImgs")
        self.actionOpenProject = QtWidgets.QAction(MainWindow)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.actionOpenVideo = QtWidgets.QAction(MainWindow)
        self.actionOpenVideo.setObjectName("actionOpenVideo")
        self.actionOpenCamera = QtWidgets.QAction(MainWindow)
        self.actionOpenCamera.setObjectName("actionOpenCamera")
        self.menu_6.addAction(self.actionOpenTarget)
        self.menu_6.addAction(self.actionOpenVideo)
        self.menu_6.addAction(self.actionOpenCamera)
        self.menu_6.addAction(self.actionOpenDataImgs)
        self.menu_6.addAction(self.actionOpenProject)
        self.menu.addAction(self.menu_6.menuAction())
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionClose)
        self.menu.addSeparator()
        self.menu_2.addAction(self.actionBaiduImage)
        self.menu_2.addAction(self.actionOpenImg)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionTFRecord)
        self.menu_2.addAction(self.actionOpenData)
        self.menu_4.addAction(self.actionTensorboard)
        self.menu_4.addAction(self.actionjupyter_Notebook)
        self.menu_5.addAction(self.actionview1)
        self.menu_5.addAction(self.actionview2)
        self.menu_5.addAction(self.actionview3)
        self.menu_Language.addAction(self.actionEn)
        self.menu_Language.addAction(self.actionCh)
        self.menu_Language.addAction(self.actionJa)
        self.menu_Help.addAction(self.actionDoc)
        self.menu_System.addAction(self.menu_Language.menuAction())
        self.menu_System.addAction(self.menu_Help.menuAction())
        self.menu_System.addSeparator()
        self.menu_System.addAction(self.actionAuthor)
        self.menu_3.addAction(self.actionImageEditor)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_System.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于安检机图像的违禁品检测"))
        self.groupBox.setTitle(_translate("MainWindow", "原始图像"))
        self.ImgLabel1.setText(_translate("MainWindow", "原始"))
        self.pushButton_openImg.setText(_translate("MainWindow", "打开图片"))
        self.pushButton_openVideo.setText(_translate("MainWindow", "打开视频"))
        self.pushButton_openCamera.setText(_translate("MainWindow", "打开摄像头"))
        self.pushButton_Start1.setText(_translate("MainWindow", "开始检测1"))
        self.pushButton_Start2.setText(_translate("MainWindow", "开始检测2"))
        self.pushButton_videoResult.setText(_translate("MainWindow", "开始检测视频流1"))
        self.pushButton_Start3.setText(_translate("MainWindow", "开始检测视频流2"))
        self.comboBox.setItemText(0, _translate("MainWindow", "最终输出结果"))
        self.comboBox.setItemText(1, _translate("MainWindow", "图像裁剪"))
        self.comboBox.setItemText(2, _translate("MainWindow", "边缘处理"))
        self.comboBox.setItemText(3, _translate("MainWindow", "灰度化"))
        self.comboBox.setItemText(4, _translate("MainWindow", "噪声处理"))
        self.comboBox.setItemText(5, _translate("MainWindow", "第一层卷积层结果"))
        self.comboBox.setItemText(6, _translate("MainWindow", "第一层池化层结果"))
        self.comboBox.setItemText(7, _translate("MainWindow", "第二层卷积层结果"))
        self.comboBox.setItemText(8, _translate("MainWindow", "第二层池化层结果"))
        self.label_to.setText(_translate("MainWindow", "to"))
        self.groupBox_2.setTitle(_translate("MainWindow", "输出结果"))
        self.ImgLabel2.setText(_translate("MainWindow", "结果"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_6.setTitle(_translate("MainWindow", "打开"))
        self.menu_2.setTitle(_translate("MainWindow", "数据集"))
        self.menu_4.setTitle(_translate("MainWindow", "训练"))
        self.menu_5.setTitle(_translate("MainWindow", "视图"))
        self.menu_System.setTitle(_translate("MainWindow", "系统"))
        self.menu_Language.setTitle(_translate("MainWindow", "语言"))
        self.menu_Help.setTitle(_translate("MainWindow", "帮助"))
        self.menu_3.setTitle(_translate("MainWindow", "编辑"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionClose.setText(_translate("MainWindow", "关闭"))
        self.actionTensorboard.setText(_translate("MainWindow", "Tensorboard"))
        self.actionBaiduImage.setText(_translate("MainWindow", "下载百度图片数据集"))
        self.actionOpenData.setText(_translate("MainWindow", "数据集目录"))
        self.actionOpenData.setToolTip(_translate("MainWindow", "打开训练集目录"))
        self.actionTFRecord.setText(_translate("MainWindow", "图片预处理与数据集制作"))
        self.actionsaa.setText(_translate("MainWindow", "saa"))
        self.actionas_2.setText(_translate("MainWindow", "编辑训练集"))
        self.actionImageEditor.setText(_translate("MainWindow", "编辑图像"))
        self.actionsda.setText(_translate("MainWindow", "sda"))
        self.actions.setText(_translate("MainWindow", "s"))
        self.actiondsa.setText(_translate("MainWindow", "dsa"))
        self.actionasdas.setText(_translate("MainWindow", "asdas"))
        self.actiondas.setText(_translate("MainWindow", "das"))
        self.actionasd.setText(_translate("MainWindow", "asd"))
        self.actionads.setText(_translate("MainWindow", "ads"))
        self.actionjupyter_Notebook.setText(_translate("MainWindow", "jupyter Notebook"))
        self.actionDocument.setText(_translate("MainWindow", "wendang"))
        self.actionview1.setText(_translate("MainWindow", "view1"))
        self.actionview2.setText(_translate("MainWindow", "view2"))
        self.actionview3.setText(_translate("MainWindow", "view3"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action2_2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.actionAskd.setText(_translate("MainWindow", "askd"))
        self.actionEn.setText(_translate("MainWindow", "英语"))
        self.actionCh.setText(_translate("MainWindow", "中文"))
        self.actionJa.setText(_translate("MainWindow", "日语"))
        self.actionAuthor.setText(_translate("MainWindow", "联系开发者"))
        self.actionDoc.setText(_translate("MainWindow", "文档"))
        self.actionBanben.setText(_translate("MainWindow", "版本信息"))
        self.actionOpenImg.setText(_translate("MainWindow", "下载到的图片目录"))
        self.actionOpenTarget.setText(_translate("MainWindow", "目标图片"))
        self.actionOpenDataImgs.setText(_translate("MainWindow", "图片数据集"))
        self.actionOpenProject.setText(_translate("MainWindow", "项目文件夹"))
        self.actionOpenVideo.setText(_translate("MainWindow", "目标视频"))
        self.actionOpenCamera.setText(_translate("MainWindow", "摄像头"))

